source 'https://rubygems.org'
ruby '2.2.1'

gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass'
gem 'simple_form'
gem 'slim-rails'

group :development, :test do
  gem 'web-console', '~> 2.0'
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'thin'
end

group :test do
  gem 'rspec-rails'
  gem 'cucumber-rails'
  gem 'selenium-webdriver'
  gem 'rspec-collection_matchers'
  gem 'capybara'
  gem 'poltergeist'
  gem 'database_cleaner', '~> 1.2.0'
  gem 'timecop'
  gem 'minitest'
end
